-- DuckDB schema
CREATE TABLE IF NOT EXISTS credit_card_raw (
  LIMIT_BAL INTEGER,
  SEX INTEGER,
  EDUCATION INTEGER,
  MARRIAGE INTEGER,
  AGE INTEGER,

  PAY_0 INTEGER, PAY_2 INTEGER, PAY_3 INTEGER, PAY_4 INTEGER, PAY_5 INTEGER, PAY_6 INTEGER,

  BILL_AMT1 INTEGER, BILL_AMT2 INTEGER, BILL_AMT3 INTEGER, BILL_AMT4 INTEGER, BILL_AMT5 INTEGER, BILL_AMT6 INTEGER,
  PAY_AMT1 INTEGER,  PAY_AMT2 INTEGER,  PAY_AMT3 INTEGER,  PAY_AMT4 INTEGER,  PAY_AMT5 INTEGER,  PAY_AMT6 INTEGER,

  LABEL INTEGER
);
